#! /usr/bin/env ruby

require "pg"
require "io/console"

class ExpenseData
  def initialize
    @connection = PG.connect(dbname: "expenses")
    setup_schema
  end

  def list_expenses
    result = @connection.exec("SELECT * FROM expenses ORDER BY created_on ASC")

    display_count(result)
    display_expenses(result) if result.ntuples > 0
  end

  def add_expense(amount, memo)
    date = Date.today
    sql = "INSERT INTO expenses (amount, memo, created_on) VALUES ($1, $2, $3)"
    @connection.exec_params(sql, [amount, memo, date])
  end

  def search_expense(search_fragment)
    sql = "SELECT * FROM expenses where memo ILIKE $1"

    results = @connection.exec_params(sql, ["%#{search_fragment}%"])

    display_count(results)
    display_expenses(results) if results.ntuples > 0
  end

  def delete_expense(id)
    sql = "SELECT * FROM expenses where id = $1"
    existing_record = @connection.exec_params(sql, [id])

    if existing_record.any?
      sql = "DELETE FROM expenses where id = $1"
      @connection.exec_params(sql, [id])

      puts "The following expense has been deleted"
      display_expenses(existing_record)
    else
      puts "There is no expense with the id '#{id}'."
    end
  end

  def delete_all_expenses
    @connection.exec('DELETE FROM EXPENSES')
    puts 'All expenses have been deleted.'
  end

  def setup_schema
    sql = "SELECT COUNT(*) FROM information_schema.tables " \
          "WHERE table_schema = 'public' AND table_name = 'expenses';"
    result = @connection.exec(sql)

    if result[0]['count'] == '0'
      @connection.exec <<~SQL
        CREATE TABLE expenses (
          id serial PRIMARY KEY,
          amount numeric(6, 2) NOT NULL CHECK (amount >= 0.01),
          memo text NOT NULL,
          created_on date NOT NULL
        );
      SQL
    end
  end

  private

  def display_count(result)
    unless result.any?
      puts "There are no expenses."
    else
      puts "there are #{result.ntuples} expenses"
    end
  end

  def display_expenses(expenses)
    total = []
    expenses.each do |tuple|
      total << tuple["amount"].to_f
      columns = [ tuple["id"].rjust(3),
                  tuple["created_on"].rjust(10),
                  tuple["amount"].rjust(12),
                  tuple["memo"] ]

      puts columns.join(" | ")
    end

    puts '-' * 50
    puts "Total #{total.inject(:+).to_s.rjust(25)}"
  end
end

class CLI
  def initialize
    @application = ExpenseData.new
  end

  def run(arguments)
    command = arguments.shift
    case command
    when "add"
      amount = arguments[0]
      memo = arguments[1]

      abort "You must provide an amount and memo." unless amount && memo

      @application.add_expense(amount, memo)
    when "list"
      @application.list_expenses
    when "search"
      search_fragment = ARGV[0]

      abort "You must provide a search term" unless search_fragment

      @application.search_expense(search_fragment)
    when "delete"
      id = ARGV[0]

      abort "You must provide an id" unless id

      @application.delete_expense(id)
    when "clear"
      puts "This will remove all expenses. Are you sure? (y/n)"
      response = $stdin.getch

      @application.delete_all_expenses if response == 'y'
    else
      display_help
    end
  end

  def display_help
    puts <<~HELP
      An expense recording system

      Commands:

      add AMOUNT MEMO [DATE] - record a new expense
      clear - delete all expenses
      list - list all expenses
      delete NUMBER - remove expense with id NUMBER
      search QUERY - list expenses with a matching memo field
    HELP
  end
end

CLI.new.run(ARGV)